# Generated by Django 4.1.4 on 2022-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawg_video_game_id', models.CharField(max_length=25)),
                ('video_game_title', models.CharField(max_length=50)),
                ('video_game_image', models.CharField(max_length=255)),
                ('completed', models.IntegerField(default=0)),
            ],
        ),
    ]
