# Generated by Django 4.1.4 on 2022-12-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_rename_user_collection_usercollection_and_more'),
        ('video_game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video_Game',
            new_name='VideoGame',
        ),
    ]
