# Generated by Django 4.1.4 on 2023-05-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_description',
            field=models.CharField(default='Brand New User :)', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='../images/base_profile_picture.jpg', upload_to='images/'),
        ),
    ]
