# Generated by Django 4.1.4 on 2023-05-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_description_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='New User', max_length=25),
        ),
    ]
