# Generated by Django 4.1.4 on 2023-06-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='../images/images/base_profile_picture.jpg', upload_to='images/'),
        ),
    ]
