# Generated by Django 4.1.4 on 2022-12-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowers',
            old_name='follower',
            new_name='follower_user',
        ),
    ]
