# Generated by Django 4.1.4 on 2022-12-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_game', '0001_initial'),
        ('user_profile', '0002_user_collection_user_profile_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('profile_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Collection',
            new_name='UserCollection',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_profile.usercollection'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follewers',
            field=models.ManyToManyField(to='followers.userfollowers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
