# Generated by Django 4.1.4 on 2022-12-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_rename_follewers_userprofile_user_follewers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_follewers',
            new_name='user_profile_follewers',
        ),
    ]
