# Generated by Django 4.1.4 on 2022-12-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_rename_user_follewers_userprofile_user_profile_follewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_profile_follewers',
        ),
    ]
