# Generated by Django 4.1.4 on 2022-12-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
