# Generated by Django 4.1.4 on 2022-12-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_userprofile_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_description',
            field=models.CharField(max_length=1000),
        ),
    ]
