# Generated by Django 4.1.4 on 2022-12-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_userprofile_profile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='collection',
        ),
    ]
