# Generated by Django 4.1.4 on 2022-12-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_remove_userprofile_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_description',
            field=models.CharField(default='Brand New User :)', max_length=1000),
        ),
        migrations.DeleteModel(
            name='UserCollection',
        ),
    ]
